### ISSUE TITLE
How to use download-dkb.py?

### ISSUE THREAD

**Issue by Cumol** [or/ledger-tools#1]
As I am a python-noob, how do I use this script?

I tried `python download-dkb.py`  and `./download.dkb.py` but both give me the following error:

```
Traceback (most recent call last):
  File "download-dkb.py", line 95, in <module>
    browser, tmp_dir = login(config)
  File "download-dkb.py", line 13, in login
    credentials = load_credentials(config)
  File "/Users/<username>/Desktop/temp/ledger-tools/common.py", line 32, in load_credentials
    output = subprocess.check_output(["gpg", "-q", "-d", config["general"]["key_file"]])
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'general'
```

*replaced my username with <username>

**Comment by Cumol** [comment]
Managed to run it and it works fine to download the .csv files automatically. Is there a reason why it only downloads the last 1-2 months of transactions?

**Comment by Cumol** [comment]
Using the `import-csv-files.sh` script requires that the folder `generated` is already created

Running that script then gives an error when importing the first file:

```
importing absa-checking-2016...
importing absa-saving-2016...
importing absa-creditcard-2016...
importing dkb-giro-2016...
importing dkb-creditcard-2016...
importing absa-checking-2017...
importing absa-saving-2017...
importing absa-creditcard-2017...
importing dkb-giro-2017...
importing dkb-creditcard-2017...
importing absa-checking-2018...
importing absa-saving-2018...
importing absa-creditcard-2018...
importing dkb-giro-2018...
importing dkb-creditcard-2018...
importing absa-checking-2019...
importing absa-saving-2019...
importing absa-creditcard-2019...
importing dkb-giro-2019...
Traceback (most recent call last):
  File "./icsv2ledger/icsv2ledger.py", line 1057, in <module>
    main(options)
  File "./icsv2ledger/icsv2ledger.py", line 1049, in main
    process_input_output(options.infile, options.outfile)
  File "./icsv2ledger/icsv2ledger.py", line 954, in process_input_output
    for line in  process_csv_lines(csv_lines):
  File "./icsv2ledger/icsv2ledger.py", line 985, in process_csv_lines
    options)
  File "./icsv2ledger/icsv2ledger.py", line 507, in __init__
    entry_date = datetime.strptime(self.date, options.csv_date_format)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 30.12.2019;"30.12.2019";"Dauerauftrag";">omitted>";"MIETE";"DE68672500201002944932";"SOLADES1HDB";"-390
```

**Comment by or** [comment]
> Managed to run it and it works fine to download the .csv files automatically. Is there a reason why it only downloads the last 1-2 months of transactions?

Yes, the default is the last 60 days. You can change this via `./download-dkb.py --from-date <YYYY-MM-DD>`. It'll only work for the last year or so for DKB, for Absa only the last 6 months.

As for the other error: I think the delimiter is not set up correctly. I have this for DKB, for example:
```
[dkb-giro]
account=Assets:Bank:DKB:Giro
currency=EUR
skip_lines=1
date=1
csv_date_format=%d.%m.%Y
ledger_date_format=%Y/%m/%d
desc=4,5
credit=8
debit=0
mapping_file=import/dkb-giro.mapping
delimiter=;
csv_decimal_comma=,
template_file=import/dkb-giro.template

[dkb-giro_addons]
purpose=5

[dkb-creditcard]
account=Assets:Bank:DKB:Credit Card
currency=EUR
skip_lines=1
date=3
csv_date_format=%d.%m.%Y
ledger_date_format=%Y/%m/%d
desc=4
credit=5
debit=0
mapping_file=import/dkb-creditcard.mapping
delimiter=;
csv_decimal_comma=,
template_file=import/dkb-creditcard.template

[dkb-creditcard_addons]
original_amount=6
```

**Comment by Cumol** [comment]
Thank you for the help with the date.

However, I have the same exact setup as you and still get the error (and the delimeter is correct).

Any idea what could cause it? I seems like something that has to do with the date

**Comment by Cumol** [comment]
Solved it. It wasn't using the icsvledgerrc file for some reason. So the import bash script did not work. 

If I run it directly from command line like so:

`./icsv2ledger/icsv2ledger.py -q -a dkb-giro -c icsv2ledgerrc transaction-history/dkb-giro-2019.csv generated/dkb-giro-2019.ledger` 

it works fine.

**Comment by or** [comment]
Ah, glad you got it working. I believe icsv2ledger would pick up the file if it started with a dot, i.e. `. icsv2ledgerrc` instead of `icsv2ledgerrc`.
